const IMAGES = {
  LOAD: '@@IMAGES_LOAD',
  LOAD_SUCCESS: '@@IMAGES_LOAD_SUCCESS',
  LOAD_FAIL: '@@IMAGES_LOAD_FAIL',
  LOAD_MORE: '@@IMAGES_LOAD_MORE',
  LOAD_MORE_SUCCESS: '@@IMAGES_LOAD_MORE_SUCCESS',
  LOAD_MORE_FAIL: '@@IMAGES_LOAD_MORE_FAIL'
};

const INPUT = {
  CHANGE: '@@INPUT_CHANGE'
};

export { IMAGES, INPUT };
